---
# molecule/vagrant/playbook2.yml
#
# Regular playbook stuff starts here
#
#
# molecule/lxd/playbook2.yml
#
# Regular playbook stuff starts here
#
#
- name: Converge
  hosts: all
  vars:
    pip_install_packages:
      - docker
    users:
      - username: ubuntu
        groups:
          - ubuntu
          # - docker
        append: true

    virtualbox_resources_mount_check: false
    virtualbox_deployment_users_home: /home/vagrant

    vagrant_version: 2.2.3
    vagrant_virtualbox_install: false

  roles:
    - role: cjsteel.virtualbox
