---
# molecule/default/playbook2.yml
#
# Regular playbook stuff starts here
#
#
- name: Converge
  hosts: all
  vars:
    pip_install_packages:
      - docker
    users:
      - username: ubuntu
        groups:
          - docker
        append: true
    vagrant_version: 2.2.3
    vagrant_virtualbox_install: false

  roles:
    - role: cjsteel.providers
