---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: virtualbox-bionic-dt
    source:
      type: image    
      server: https://christopher-P1:8443              
      alias: bionic-dt
    profiles:
      - default
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: lxd
verifier:
  name: testinfra
  lint:
    name: flake8
