---
# file: project/virtualbox.yml

- hosts: virtualbox
  become: false
  gather_facts: true
  pre_tasks:

    - set_fact: fact_role_name="{{ lookup('env','ANSIBLE_ROLE_NAME') }}"
    - debug: var=fact_role_name

    - set_fact: fact_role_path="{{ lookup('pipe','pwd') }}/roles/virtualbox"
    - debug: var=fact_role_path

  roles:

    - virtualbox
